# Generated by Django 3.2.6 on 2022-05-07 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('secretKey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dateOfPuja', models.DateTimeField()),
                ('total_pay', models.CharField(max_length=50)),
                ('bookingDoneAt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfPuja', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(default=0, validators=[main.models.minMax2])),
                ('imageUrl', models.TextField(blank=True, default='https://image.shutterstock.com/image-vector/vector-graphic-illustration-indian-pandit-260nw-1803127855.jpg', null=True)),
                ('introText', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('reviewText', models.TextField(verbose_name='Reviews Text')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('yourRating', models.IntegerField(default=0, validators=[main.models.minMax3])),
                ('pujaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.puja')),
            ],
        ),
        migrations.CreateModel(
            name='Pandit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.TextField(max_length=2000, verbose_name='Pandit Img Url')),
                ('nameOfPandit', models.CharField(max_length=50)),
                ('experience', models.IntegerField(default=0, validators=[main.models.minMax])),
                ('panditDescription', models.TextField(default='One of the best Pandit available at panditMitra.')),
                ('pujaAssigned', models.ManyToManyField(default=None, related_name='pujas', to='main.Order')),
                ('pujaNames', models.ManyToManyField(blank=True, default=None, related_name='pujaNames1', to='main.Puja')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pujaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.puja'),
        ),
    ]
