# Generated by Django 3.2.6 on 2022-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPujaNnames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pujassName', models.ManyToManyField(blank=True, to='main.Puja', verbose_name='Puja names')),
            ],
        ),
        migrations.AlterField(
            model_name='pandit',
            name='pujaAssigned',
            field=models.ManyToManyField(default=None, related_name='pujas', to='main.myPujaNnames'),
        ),
    ]
