# Generated by Django 3.2.6 on 2022-05-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220508_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='pujaAssigned',
        ),
    ]
