# Generated by Django 3.2.6 on 2022-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pandit_pujaassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='pujaAssigned',
            field=models.ManyToManyField(default=None, related_name='pujas', to='main.myPujaNnames'),
        ),
    ]
