# Generated by Django 3.2.6 on 2022-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220424_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit',
            name='imageUrl',
            field=models.URLField(max_length=1000, verbose_name='Pandit Img Url'),
        ),
    ]
