# Generated by Django 3.2.6 on 2022-05-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pandit_pujaassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit',
            name='pujaAssigned',
            field=models.ManyToManyField(blank=True, default=None, related_name='pujas', to='main.Order'),
        ),
    ]
