# Generated by Django 3.2.6 on 2022-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pandit_pujaassigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialProvided',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materialName', models.CharField(max_length=100)),
            ],
        ),
    ]
