# Generated by Django 3.2.6 on 2022-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_materialprovided'),
    ]

    operations = [
        migrations.AddField(
            model_name='puja',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='puja',
            name='subCategories',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
