# Generated by Django 3.2.6 on 2022-04-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
