# Generated by Django 3.2.6 on 2022-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='puja',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puja',
            name='imageUrl',
            field=models.TextField(blank=True, default='https://image.shutterstock.com/image-vector/vector-graphic-illustration-indian-pandit-260nw-1803127855.jpg', null=True),
        ),
        migrations.AddField(
            model_name='puja',
            name='introText',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
