# Generated by Django 3.2.6 on 2022-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220429_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='panditDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
