# Generated by Django 3.2.6 on 2022-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_myuser_secretkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puja',
            name='panditName',
        ),
        migrations.AddField(
            model_name='pandit',
            name='pujaNames',
            field=models.ManyToManyField(blank=True, default=None, related_name='pujaNames1', to='main.Puja'),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='panditDescription',
            field=models.TextField(default='One of the best Pandit available at panditMitra.'),
        ),
    ]
