# Generated by Django 3.2.6 on 2022-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220506_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='pujaAssigned',
            field=models.ManyToManyField(blank=True, default=None, related_name='pujas', to='main.Order'),
        ),
    ]
