# Generated by Django 3.2.6 on 2022-05-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pandit_pujaassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='pujaAssigned',
        ),
    ]
